/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://ap-nexus-01.apollon.de/repository/prj-libs-snapshot/")
    }

    maven {
        url = uri("https://ap-nexus-01.apollon.de/repository/ext-release-local/")
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
