/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "discord-html-transcripts"
include(":transcripts-core")
include(":transcripts-javacord")
include(":transcripts-kord")
include(":transcripts-jda")
